version: '3' #Docker-compose version
services: # Lista de servicios
  flask_app: #servicio/app de flask
    build: # Lista de parámetros desde los cuales construir
      context: . #contexto
      dockerfile: Dockerfile #archivo de Dockerfile
    ports: #puerto contenedor:puerto host
      - "5005:5005"
    restart: always #en caso de error o falla
    volumes:
      - .:/clase
    env_file:
      - .env
    # depends_on:
    #   - mysql_db
    container_name: flask_principal  
  mysql_db:
    image: mysql:5.7  # Use the official MySQL 5.7 image from Docker Hub
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
      MYSQL_DATABASE: alchemy_b  # Create a database named 'mydatabase'
      MYSQL_USER: db_user  # Create a MySQL user 'myuser'
      MYSQL_PASSWORD: root  # Set the password for 'myuser'
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306 for MySQL
    restart: always  # Restarts the MySQL container if it stops or crashes
    container_name: mysql_database
