version: '3' #Docker-compose version
services: # Lista de servicios
  flask_app: #servicio/app de flask
    build: # Lista de parámetros desde los cuales construir
      context: . #contexto
      dockerfile: Dockerfile #archivo de Dockerfile
    ports: #puerto contenedor:puerto host
      - "5005:5005"
    restart: always #en caso de error o falla
    volumes:
      - .:/clase
    env_file:
      .env
    depends_on:
      - mysql_db
    container_name: flask_principal
  



