"""migracion inicial

Revision ID: a61967547289
Revises: 
Create Date: 2023-09-05 20:20:45.795960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a61967547289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('usuario')
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacimiento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.Integer(), nullable=True))
        batch_op.drop_column('tel')
        batch_op.drop_column('is_active')
        batch_op.drop_column('domicilio')
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('domicilio', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tel', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('telefono')
        batch_op.drop_column('activo')
        batch_op.drop_column('nacimiento')

    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=1406), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    op.drop_table('user')
    # ### end Alembic commands ###
